env:
  BUILDKITE_JOBTYPE: "Manual"
steps:
  - block: "Testing Parameters"
    fields:
      - select: "test profile"
        key: "PLATFORM"
        options:
          - label: "iOS - SG - Regression"
            value: "ios_sg_regression_single"
          - label: "iOS - TH - Regression"
            value: "ios_th_regression_single"
          - label: "Android - SG Regression"
            value: "android_sg_regression_single"
          - label: "Android - TH Regression"
            value: "android_th_regression_single"
      - select: "env"
        key: "ENV"
        options:
          - label: "SG - SIT"
            value: "sgsit"
          - label: "SG - DEV"
            value: "sgdev"
          - label: "TH - DEV"
            value: "thdev"
      - text: "build version"
        key: "BUILDVER"
        default: "latest"
  - label: "Run Test"
    key: "test"
    commands:
      - "buildkite-agent meta-data set TEST_RESULT true"
      - "./Script/auto_test_browserstack_appcenter_integrate.bash \
      $(buildkite-agent meta-data get PLATFORM) \
      $(buildkite-agent meta-data get BUILDVER) \
      $(buildkite-agent meta-data get ENV) || buildkite-agent meta-data set TEST_RESULT false"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    plugins:
      - docker#v3.5.0:
          image: "929795455535.dkr.ecr.ap-southeast-1.amazonaws.com/devops/u-qa-automation:latest"
          always-pull: true
          environment:
            - BROWSERSTACK_USER
            - BROWSERSTACK_PWD
            - APPCENTER_TOKEN
    artifact_paths: "./target/surefire-reports/emailable-report.html"
  - label:
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    commands:
      - "cd .buildkite/scripts/"
      - "buildkite-agent artifact download target/surefire-reports/emailable-report.html . --step 'Run Test'"
      - "./send-slack-notification.sh target/surefire-reports/emailable-report.html \
      $(buildkite-agent meta-data get ENV) \
      $(buildkite-agent meta-data get PLATFORM) \
      $(buildkite-agent meta-data get BUILDVER) \
      $(buildkite-agent meta-data get TEST_RESULT)"
    depends_on:
      - step: "test"
        allow_failure: true
    plugins:
      - docker#v3.5.0:
          image: "curlimages/curl"
          always-pull: true
          environment:
            - BUILDKITE_SLACK_TOKEN
            - BUILDKITE_BUILD_NUMBER
            - BUILDKITE_JOBTYPE
            - BUILDKITE_PIPELINE_SLUG
          user: root
    
